plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://thingking-machine.github.io
baseurl: /grok

title: Thingking Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Thingking-Machine
  verb: Thingking
  instructions_file: grok_thingking.md
  token: grok
  server: https://localhost:443
  apiUrl: https://api.x.ai/v1/chat/completions

app:
  worker_name: grokapi.js

lm:
  model: grok-3-mini
  max_completion_tokens: 131071
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95
  reasoning_effort: high


github_settings:
  owner: thingking-machine
  repo: thingking_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
